version: "2"

networks:
  tasks:
  k6:
  grafana:

services:
  tasks-api:
    build:
      context: ./task-service
      dockerfile: ./Dockerfile
    image: telnoiko/tasks-api:dev
    container_name: "tasks-api"
    hostname: "tasks-api"
    networks:
      - tasks
    ports:
      - "1323:1323"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  db:
    image: postgres:15.2-alpine
    restart: always
    networks:
      - tasks
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: tasks
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./task-service/db/db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
